apiVersion: v1
kind: Service

metadata:
  name: deployment-service
  namespace: deployment-demo

spec:
  selector:
    app: deployment-app

  ports:
    - port: 3000
      targetPort: 3000

  type: NodePort